### ISSUE TITLE
 Expected spy dispatch to have been called with [ Object(...) ] but it was never called.

### ISSUE THREAD

**Issue by guilhermejcgois** [angular-redux/store#473] opened 2017-10-23 15:03 UTC
### This is a...

* [ ] feature request
* [ ] bug report
* [x] usage question

### What toolchain are you using for transpilation/bundling?

* [x] [at]angular/cli
* [ ] Custom [at]ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 6.11.2
Typescript Version: 2.3.4
Angular Version: 4.4.6
@angular-redux/store version: 6.5.7
@angular/cli version: (if applicable) 1.4.9
OS: win32 x64 (Windows 10)

### Link to repo showing the issus
(optional, but helps _a lot_)
Sorry, is a private repo, but I think that the important parts is:
```
  // component.spec.ts
  ...
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        AppRoutingModuleStub,
        SharedModule,
        NgReduxTestingModule,
        WalletModule
      ],
      providers: [
        { provide: APIService, useClass: APIServiceStub.Dummy },
        PortfolioAPIActions,
        TranslateStore
      ]
    })
    .compileComponents();

    MockNgRedux.reset();
  }));
  ...
  it('should load data on creation', () => {
    const spy = spyOn(MockNgRedux.mockInstance, 'dispatch');
    TestBed.createComponent(Component);

    expect(spy).toHaveBeenCalledWith({
      type: APIActions.LOAD_DATA,
      meta: { stateType: STATE_TYPES.DATA },
      payload: null,
    });
  });

  // component.ts
  ...
  constructor(
    private ngRedux: NgRedux<AppState>,
    private apiActions: APIActions
  ) {
    super();
    this.apiActions.loadData(STATE_TYPES.DATA);
  }
  ...
```

### Expected Behaviour:
The spy dispatch was called.

### Actual Behaviour:
The spy dispatch was never called.

### Additional Notes:
Am I doing something wrong or missing something? Isn't so clear how to use the testing module, only seeing the spec on the example doesn't help so much, do u will write some wiki or something like about how to properly write unit tests with angular-redux/store? Maybe I can help to write them, but I need to know how to write and execute 😅

**Comment by e-schultz** [comment] 2017-10-25 13:46
If you move the `const spy = spyOn(MockNgRedux.mockInstance, 'dispatch');` to after the create instance, does it work? 

I think when you are doing create component - the Angular DI takes over and ends up creating a new instance of redux which might be causing the spy you had setup to get over written.

**Comment by guilhermejcgois** [comment] 2017-10-25 18:51
Thanks for the quick response @e-schultz ! I have tried too, but no success... Make sense what u say, I have tried to assign the spy before createComponent and after (together), but sadly got this:
```
Usage: spyOn(<object>, <methodName>)
        Error: <spyOn> : dispatch has already been spied upon
```

**Comment by guilhermejcgois** [comment] 2017-10-25 18:52
Well, we have others componentes with redux to test too, maybe someone here can found a solution, I'll try to setup a little project in this weekend to test and see with succeed

**Comment by gregkopp** [comment] 2017-10-30 17:51
If you could build a plunkr or something to demonstrate the behavior, that would help. I'd spend the time trying to recreate it myself, but there may be other factors here that you weren't able to show that could affect the behavior. I've been very successful in getting tests to run, but I haven't tried this specific setup.

**Comment by e-schultz** [comment] 2017-11-08 17:41
@guilhermejcgois looking at your code again, I noticed that you are firing things off in the constructor, and that you are also having your component inherit from something else - wondering if this could be the cause of some of the issues.

I'm sort of assuming that 

* `this.apiActions.loadData(STATE_TYPES.DATA);` is a service - that is calling the store.dispatch?
* you have replaced that with a dummy/mock 

```ts
 { provide: APIService, useClass: APIServiceStub.Dummy }
```

seems like for this test you would want to spyOn apiActions.loadData to verify if it was called

**Comment by guilhermejcgois** [comment] 2017-11-09 13:54
@e-schultz I think that the super class isn't the problem, we only use him to manage the subscriptions made in the component...

But spy the loadData instead works better, fixed by now.... Thanks for the help, great work with this lib!! 😄

**Comment by SMHFandA** [comment] 2017-11-13 06:43
It is bad practice fetching data in component constructor. I tried do this and also have a lot problem with tests. I thing, in future you have to avoid this behavior according Angular documentation: https://angular.io/guide/lifecycle-hooks#oninit

> Don't fetch data in a component constructor. You shouldn't worry that a new component will try to contact a remote server when created under test or before you decide to display it. Constructors should do no more than set the initial local variables to simple values.

**Comment by e-schultz** [comment] 2017-12-19 18:55
@guilhermejcgois glad to help - if I'm understanding correctly this is no longer an issue, going to close this. If you have any other questions / problems feel free to reach out.

**Closed by e-schultz** 2017-12-19 18:55 UTC
