### ISSUE TITLE
Expression changed after it was checked error in Angular 4, but not 2.

### ISSUE THREAD

**Issue by Bigless27** [angular-redux/store#428] opened 2017-06-15 14:27 UTC
### This is a...

* [ ] feature request
* [x] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [ ] @angular/cli
* [x] Webpack 
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 7.0.0
Typescript Version: 2.1.6
Angular Version: 4.2.2
@angular-redux/store version: ^6.0.1
@angular/cli version: (if applicable)
OS:

### Link to repo showing the issus
(optional, but helps _a lot_)
N/A

### Actual Behaviour:
When having a value change in a redux's observable subscribe method like visit in the example below

```
                  @select step$	
                   this.step$
				.takeUntil(this.ngUnsubscribe)
				.subscribe(res => {
					var review = this.ngRedux.getState().review;
					this.visit = res;
			})
```

I get a expression changed after it was checked error in my html on any element that targets visit. like below.
```
<button type="button" [ngClass]="{'color-blue': visit === 1 }" >
 </button>
```

Even if I do the same behavior in another observable. e.q. changing the visit in an observable. I don't get an expression changed after it was checked error.

### Expected Behaviour:
Value updates in the component and on the DOM. When I used Angular 2 there were no errors but after upgrading to 4.2.2 I get errors :(.

### Stack Trace/Error Message:

Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'. 

### Additional Notes:
Been at this all day trying to figure out what is causing this and I'm pretty sure that this is taking place in the redux observables subscribe method. Also, using a manual change detection like `ref.detectChanges()` silences the errors, but, looks like it halts executions of my observable subscribing to the next value until after that round of change detection occurs. Any help would be greatly appreciated!!

**Comment by e-schultz** [comment] 2017-06-21 15:12
Where in your component are you doing the subscribe? Could you provide a more complete code example - as also curious to why you are using select, but then a `getState` in the subscribe (don't think the use of getState is the issue though).

**Comment by Bigless27** [comment] 2017-06-21 18:39
I don't believe this is a redux issue anymore but an angular 4.2.x issue. https://github.com/angular/angular/issues/17572, there's the current issue on the angular GitHub. When I downgrade to 4.1.x everything works fine. I use getState() because I have two properties on the redux object. 
```
export interface IProgressState {
	step: number;
	review: boolean
}

```

I want to get both the step and the reviews value. 
```
@select() review$
@select() step$

this.step$
 .takeUntil(this.ngUnsubscribe)
 .subscribe(res => {
  var review = this.ngRedux.getState().review;
  this.visit = res;
}


```

**Comment by e-schultz** [comment] 2017-06-22 12:40
You could use something like 

```js
this.step$
.withLatestFrom(this.review$,(step,review)=>{ 
return { 
  // do something with step and review
}
}).subscribe(res=> { });
```

with the above - any time step changes, it will get the latest value of review.
Or, if you wanted to do something if either step, or review changes - `combineLatest`

Learn-rxjs has good examples for [combineLatest](https://www.learnrxjs.io/operators/combination/combinelatest.html) and [withLatestFrom](https://www.learnrxjs.io/operators/combination/withlatestfrom.html)

Also - in the `.subscribe` - is this being done in the constructor? in the ngOnInit? depending on where you are setting up the subscription - this could impact things for getting that error. 

That said - looking through the issue that you linked, there does seem to be a regression that has happened in Angular itself, as other people are reporting similar behaviour, even without redux involved.

If there is anything else I can do to help, let me know - otherwise I will close this issue, but I'll wait for your response first.

**Comment by KevinRattan** [comment] 2017-06-25 12:35
Finally had a bit of time to play around with this. Rejigged the code a little to use an array of booleans (rather than an inline comparison) to set classes and visibility... and I have at least narrowed down my problem. 

It arises when an action triggered from routing triggers two different things - getting and showing the data for panel 2, while hiding panel 1. Hiding and showing panels (and changing up/down icons) via clicking on the header is not a problem - works as before. Having it triggered by a routerLink inside one of the panels causes the exception in the following code:

<span class="glyphicon pull-right" 
  [ngClass]="{'glyphicon-chevron-up' : (ui$ | async)?.visiblePanels[VisiblePanel.IngredientTypes], 'glyphicon-chevron-down' : !((ui$ | async)?.visiblePanels[VisiblePanel.IngredientTypes])}"></span>

I will try to work up a simple example if I get the chance, but it would take some time - there's a lot of unpicking to do, with child routes etc in the mix.

At the moment, I'm just going to stick with version 4.1.3, where the code runs without problems.

**Comment by KevinRattan** [comment] 2017-07-02 15:45
I've been contributing to the thread over at Angular itself - and have reached a point where I think I have isolated the problem arising from the switch from 4.1.3 to 4.2.  

My UI reducer manages visibility, and is the source of the state change that's triggering the error. Here is a cut-down version of the reducer, showing the relevant actions:

export const userInterfaceReducer = (state = INITIAL_UI(), action: any) => {
    switch (action.type) {
        case IngredientActions.LIST_INGREDIENTS:
            if (action.hideTypes) {
                return Object.assign(state, { visiblePanel: VisiblePanel.Ingredients });
            }
            return state;
        default:
            return state;
    }
}

When I run this in 4.1.3 it works - first, the LIST_INGREDIENTS action fires and the new state is returned; then the UPDATE_LOCATION action fires, and the default case is hit, returning the same state.

When I run it in 4.2, the order or actions is reversed. The UPDATE_LOCATION action fires first, returning the old state from default. Then LIST_INGREDIENTS fires, returning the new (changed) state - and the error is raised.

I am completely open to the idea that I have done something dumb and this isn't an actual bug - but if so, what?

**Comment by defra91** [comment] 2017-07-03 08:19
Same problem here. To fix it I had to roll back from 4.2.2 to 4.1.3

**Comment by moarsel** [comment] 2017-07-10 14:02
(we're having this problem with ngrx as well)

**Comment by mswilson4040** [comment] 2017-07-27 20:02
Upgraded to 4.3.1 and the issue is still present.

**Comment by Bigless27** [comment] 2017-07-27 21:25
Rolling the version back to 4.1.3 fixed it!

**Closed** 2017-07-27 21:26 UTC

**Comment by Bigless27** [comment] 2017-07-27 21:30
@e-schultz Thank you for that great solution. My observable skills have greatly improved since then. Sorry about getting back to you late but the `.subscribe` are coming from my `ngOnInit(){}`

**Comment by saravanakumar-sudo** [comment] 2020-02-27 09:44
I am also facing the same issues. So then i tried like this. Its working fine for me.
**Step 1:**
import { Component, OnInit, ChangeDetectorRef, AfterContentChecked } from '@angular/core';
**_step 2:_**
export class RegisterComponent implements OnInit, AfterContentChecked {
 constructor(private cdRef: ChangeDetectorRef) {}
 ngOnInit() {---}

  ngAfterContentChecked() {
    this.cdRef.detectChanges();
  }
}
