### ISSUE TITLE
About MockNgRedux

### ISSUE THREAD

**Issue by gviligvili** [angular-redux/store#435] opened 2017-07-06 09:06 UTC
### This is a...

* [X ] usage question

### What toolchain are you using for transpilation/bundling?

* [X ] @angular/cli

In my test suit : 

```
beforeEach(() => {

 TestBed.configureTestingModule({
            imports: [
                HttpModule,
                NgReduxTestingModule
            ],
            providers: [
                MockBackend,
                BaseRequestOptions,
                {
                    provide: Http,
                    useFactory: (mockBackend, options) => {
                        return new Http(mockBackend, options);
                    },
                    deps: [MockBackend, BaseRequestOptions]
                },
                ArticlesActions
            ]
        });

        MockNgRedux.reset();
    });
```

In a test suite, I use a spy this way : 
`        var funcSpy = spy(MockNgRedux.getInstance(), "dispatch");
`

In the second test, when I try to use a spy again - it says that the spy already exists.
`TypeError: Attempted to wrap dispatch which is already wrapped`
so besides doing some clearing logics in MockNgRedux.reset(), shouldn't it also clear the object himself?

Think about it, in large applications, if a teammate wont clear the spy out of "mockNgRedux.dispatch",  it will be horrible to find it.

If I'm doing something wrong, please guide me :)
Thanks !

**Comment by e-schultz** [comment] 2017-07-06 17:17
Hi,

I'll take a look into this and see if it's something that `reset` can clean up automatically. According to the Jasmine docs - spies should clean up after each `it` block on it's own.

In the meantime, could something like:

```js
beforeEach(function () {
  this._originalMethod = obj.prototype.method;
  spyOn(obj.prototype, 'method');
});

afterEach(function () {
  obj.prototype.method = this._originalMethod;
});
```

work - came across this suggestion in the [jasmine issues](https://github.com/jasmine/jasmine/issues/236) 

Thanks for bringing this to my attention though, I will try to look into it soon.

**Comment by SethDavenport** [comment] 2017-07-07 03:18
sounds reasonable - I'll take a look on saturday

**Comment by SethDavenport** [comment] 2017-07-12 02:54
The fix might be as simple as resetting the static instance to a new object when .reset() is called?

**Comment by gregkopp** [comment] 2017-07-28 13:00
I'm not sure if this is related, or I am just trying to implement this in a bad way. We just upgraded to 6.5.7 and I am refactoring to use the new MockNgRedux and the @dispatch decorators.

I'm also trying to spyOn the dispatch function, but none of the spies are returning.

```
import { NgRedux } from '@angular-redux/store';
import { MockNgRedux } from '@angular-redux/store/testing';

describe('State Service: Documents', () => {
  let mockNgRedux: NgRedux<any> = MockNgRedux.getInstance();
  let stateService: DocumentsStateService;
  const isArchiveLoadedStub = MockNgRedux.getSelectorStub(['documentsState', 'isArchiveLoaded']);

  beforeEach(() => {
    isArchiveLoadedStub.next(true);
    stateService = new DocumentsStateService();

  it('should dispatch a documents archive requested action', () => {
    const expectedAction = {
      type: DocumentsTypes.DOCUMENTS_ARCHIVE_REQUESTED
    };
    spyOn(mockNgRedux, 'dispatch');
    stateService.onDocumentsArchiveRequest();
    expect(mockNgRedux.dispatch).toHaveBeenCalledWith(expectedAction);
  });
}
```

The call to **stateService.onDocumentsArchiveRequest();** is a @dispatch decorated function:

```
@Injectable()
export class DocumentsStateService {
  @dispatch() onDocumentsArchiveRequest = DocumentsActions.onDocumentsArchiveRequest;
}
```

With the actions:
```
export abstract class DocumentsActions {
  static readonly onDocumentsArchiveRequest = () => ({ type: DocumentsTypes.DOCUMENTS_ARCHIVE_REQUESTED });
}
```

Maybe I'm doing something wrong and I'm just not seeing it.

**Comment by gregkopp** [comment] 2017-07-31 14:20
Well, this is getting interesting, as a bug that was previously fixed has reared it's head again.

If I run my unit tests in isolation, it works fine. However, if I run them with the rest of the application suite, they fail. This happened before when we mixed how we were mocking redux.

**Comment by e-schultz** [comment] 2017-07-31 14:51
Hi Greg,

Knowing that it fails the rest of the suite is good information, I'll take a look into it.

However, for the unit test on onDocumentsArchiveRequest - since a POJO is being replaced, instead of needing to spyOn the instance, you could do a check of:

```js
 it('should dispatch a documents archive requested action', () => {
    const expectedAction = {
      type: DocumentsTypes.DOCUMENTS_ARCHIVE_REQUESTED
    };

    let actualAction = stateService.onDocumentsArchiveRequest();
    expect(actualAction).toEqual(expectedAction);
  });
}
```

I'm going to try and work on some integration tests soon to try and be able to reproduce these issues. Bit of a case of 'unit tests work, but not enough integration tests' - and it's starting to surface issues like this. 

Thanks for the information

**Comment by gregkopp** [comment] 2017-07-31 15:14
To be clear, when it's these tests that fail when run with the entire suite.

This behavior was originally noticed a while back and @SethDavenport had resolved it in Issue #413. But those circumstances were a little different than this.

I'm wondering, however, will I need to use the TestBed for these tests, to set the mock provider, since this class is now using the @dispatch decorator and is not directly injecting redux in the constructor.

I tried your suggestion, but the compiler is now unhappy. The aforementioned function above is a void return type.

**Comment by gregkopp** [comment] 2017-07-31 16:13
Your suggestion won't work for me, at least not in the current incarnation of these tests. Part of my tests require updating a value in the mock store and I need to update the stub selector with a different value.

I need to dive into this a little deeper.

**Comment by gregkopp** [comment] 2017-07-31 17:10
I figured out what I was doing wrong. I wasn't resetting the MocNgRedux before each test:

```
beforeEach(() => {
    MockNgRedux.reset();
    isArchiveLoadedStub.next(true);
    stateService = new DocumentsStateService();
   ...
```

Just an oversight on my part.

**Comment by e-schultz** [comment] 2017-09-07 12:28
Ok, closing out this issue since it seems to be resolved. Feel free to re-open if you have any problems again.

**Closed by e-schultz** 2017-09-07 12:28 UTC
