### ISSUE TITLE
TypeScript is complaining about my thunk action

### ISSUE THREAD

**Issue by born2net** [angular-redux/store#264] opened 2016-12-01 08:14 UTC
I am getting an error in TS of:
```
Error:(15, 29) TS2345:Argument of type '(dispatch: any) => void' is not assignable to parameter of type 'Action'.
  Property 'type' is missing in type '(dispatch: any) => void'.
```

and I am not sure why as I am using a thunk middleware which seems to work fine.

my config is:

```
export class AppModule {
    constructor(private ngRedux: NgRedux<IAppState>, private devTools: DevToolsExtension) {
        const reducers = combineReducers({notify});
        const middlewareEnhancer = applyMiddleware(<any>thunkMiddleware);
        const applyDevTools = () => devTools.isEnabled() ? devTools.enhancer : f => f;
        const enhancers:any = compose(middlewareEnhancer, applyDevTools);
        const createStoreWithEnhancers = enhancers(createStore);
        const store = createStoreWithEnhancers(reducers);
        ngRedux.provideStore(store);
    }
}

```

and my thunk dispatching via:

```
export class MyComp {
    constructor(private store: NgRedux<any>) {
       this.store.dispatch(this.act('123'));
    }

    private act = (i_value) => {
        return (dispatch) => {
            setTimeout(() => {
                dispatch({type: 'BB', payload: i_value})
            }, 5000)
        }
    }
}

```

but TypeScript is expecting an action with a TYPE, but this is a thunk so I am not sure why ts defined with a type.. again error is:

```
Error:(15, 29) TS2345:Argument of type '(dispatch: any) => void' is not assignable to parameter of type 'Action'.
  Property 'type' is missing in type '(dispatch: any) => void'.
```

regards

Sean

**Comment by SethDavenport** [comment] 2016-12-02 04:43
This appears to be a duplicate of #211. The workaround d is to call `dispatch<any>(theThunk)`

**Comment by born2net** [comment] 2016-12-02 04:45
Thanks for posting but I'm wondering why do we need a work around and why it can't be fixed...
regards

**Comment by negue** [comment] 2017-03-24 08:52
I think, it would be better if `NgRedux<RootState>.dispatch` had the Redux-Type `Dispatch<S>` itself (instead of `<A extends Redux.Action>(action: A) => any` ), cause middlewares like `redux-thunk` extended this Type and then we wouldn't need to do a `dispatch<any>(theThunk)`

**Comment by SethDavenport** [comment] 2017-05-12 13:08
Yes you're absolutely right. Didn't see this because my inbox is a disaster.

**Closed** 2017-05-12 15:23 UTC
Labels: in progress
